version: '2'
services:
  devbox:
    build: .
    hostname: devbox
    environment:
      - AUTHORIZED_GH_USERS="ksoderstrom"
    volumes:
      - code:/home/dev/code
    ports:
      - "31122:22"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD:
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  code:
  postgres:
