version: '2'
services:
  devbox:
    build:
      context: .
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    hostname: devbox
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/ks/.ssh:/home/dev/.ssh
      - /home/ks/.netrc:/home/dev/.netrc
      - code:/home/dev/code
    ports:
      - "31122:22"
      - "33000:3000"
      - "34000:4000"
      - "35000:5000"
      - "34567:4567"
      - "31125:31125/udp"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6-alpine
    command: postgres -c shared_buffers=2GB -c effective_cache_size=4GB -c synchronous_commit=off
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD:
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  code:
  postgres:
